packer {
  required_plugins {
   xenserver= {
      version = ">= v0.7.0"
      source = "github.com/ddelnano/xenserver"
    }
  }
}

variable "remote_host" {
  type        = string
  description = "The ip or fqdn of your XCP-ng. It must be the master"
  sensitive   = true
  default     = "192.168.1.12"
}

variable "remote_username" {
  type        = string
  description = "The username used to interact with your XCP-ng"
  sensitive   = true
  default     = "root"
}

variable "remote_password" {
  type        = string
  description = "The password used to interact with your XCP-ng"
  sensitive   = true
  default     = "pw"
}

variable "sr_iso_name" {
  type        = string
  description = "The ISO-SR to packer will use"
  default     = ""
}

variable "sr_name" {
  type        = string
  description = "The name of the SR to packer will use"
  default     = "Local storage"
}

source "xenserver-iso" "autogen" {
  iso_checksum      = "013f5b44670d81280b5b1bc02455842b250df2f0c6763398feb69af1a805a14f"
  iso_url           = "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-12.5.0-amd64-netinst.iso"

  sr_iso_name    = var.sr_iso_name
  sr_name        = var.sr_name
  tools_iso_name = ""

  remote_host     = var.remote_host
  remote_password = var.remote_password
  remote_username = var.remote_username

  http_directory = "http"
  http_port_max   = 8443
  http_port_min   = 8443
  ip_getter = "tools"

  boot_command =  [
        "<wait><wait><wait><esc><wait><wait><wait>",
        "/install.amd/vmlinuz ",
        "initrd=/install.amd/initrd.gz ",
        "auto=true ",
        "domain= ", 
        "url=http://{{.HTTPIP}}:{{.HTTPPort}}/preseed.cfg ",
        "hostname=ubuntu ",
        "interface=auto ",
        "vga=788 noprompt quiet--- <enter>"
  ]

  clone_template = "Debian Bookworm 12"
  vm_name        = "3l-hl-deb12-template"
  vm_description = "My first xcp-ng template with packer"
  vcpus_max	 = 2
  vcpus_atstartup = 2
  vm_memory      = 2048 #MB
  network_names = ["Infranet"]
  disk_size      = 250480 #MB
  disk_name      = "debian_disk"
  vm_tags        = ["Generated by Packer on ${formatdate("YYYYMMDD", timestamp())}"]

  ssh_username            = "vagrant"
  ssh_password            = "vagrant"
  ssh_wait_timeout        = "60000s"
  ssh_handshake_attempts  = 10000

  output_directory = "packer-debian-12"
  keep_vm          = "never"
  format = "xva_compressed"
}

build {
  sources = ["xenserver-iso.autogen"]
}
