packer {
  required_plugins {
   xenserver= {
      version = ">= v0.7.0"
      source = "github.com/ddelnano/xenserver"
    }
  }
}

variable "remote_host" {
  type        = string
  description = "The ip or fqdn of your XCP-ng. It must be the master"
  sensitive   = true
  default     = "192.168.1.12"
}

variable "remote_username" {
  type        = string
  description = "The username used to interact with your XCP-ng"
  sensitive   = true
  default     = "root"
}

variable "remote_password" {
  type        = string
  description = "The password used to interact with your XCP-ng"
  sensitive   = true
  default     = "pw"
}

variable "sr_iso_name" {
  type        = string
  description = "The ISO-SR to packer will use"
  default     = "ubuntu-24.04-live-server-amd64.iso"
}

variable "sr_name" {
  type        = string
  description = "The name of the SR to packer will use"
  default     = "Local storage"
}

source "xenserver-iso" "autogen" {
  iso_checksum      = "8762f7e74e4d64d72fceb5f70682e6b069932deedb4949c6975d0f0fe0a91be3"
  iso_url           = "https://releases.ubuntu.com/24.04/ubuntu-24.04-live-server-amd64.iso"

  sr_iso_name    = var.sr_iso_name
  sr_name        = var.sr_name
  tools_iso_name = ""

  remote_host     = var.remote_host
  remote_password = var.remote_password
  remote_username = var.remote_username

  http_directory = "http"
  http_port_max   = 8443
  http_port_min   = 8443
  ip_getter = "tools"

  boot_command = [
	"e<wait><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del><del>", 
	"linux /casper/vmlinuz --- autoinstall ds='nocloud-net;s=http://{{ .HTTPIP }}:{{ .HTTPPort }}/'<enter> ",
	"initrd /casper/initrd<wait>", 
	"<F10>"]

  clone_template = "Ubuntu Focal Fossa 20.04"
  vm_name        = "Ubuntu-2404-template"
  vm_description = "My first xcp-ng template with packer"
  vcpus_max	 = 2
  vcpus_atstartup = 2
  vm_memory      = 2048 #MB
  network_names = ["Infranet"]
  disk_size      = 250480 #MB
  disk_name      = "Ubuntu-2404-template-disk"
  vm_tags        = ["Generated by Packer on ${formatdate("YYYY-MM-DD", timestamp())}"]

    ssh_username            = "vagrant"
  ssh_password            = "vagrant"
  ssh_wait_timeout        = "60000s"
  ssh_handshake_attempts  = 10000

  output_directory = "ubuntu-2404"
  keep_vm          = "never"
  format = "xva_compressed"
}

build {
  sources = ["xenserver-iso.autogen"]
}
